### ISSUE TITLE
Automate Doulevo release

### ISSUE THREAD

**Issue by R4meau** [doulevo/doulevo#20]
We need to simplify NPM package publishing and GitHub releases so we can focus on development rather than deployment.

Here are my suggestions:
- Uses GitHub Actions
- Runs on
  - A push to the `main` branch
  - A manual run from the GitHub interface
- It should only build and deploy when it detects version changes from the `package.json` file
- After building, it should publish to NPM and create a new GitHub release using the build artifacts

It will require we set the NPM_TOKEN and the GITHUB_TOKEN secrets from the GitHub interface.

Note: this is different from continuous integration, for which we should create a new GitHub action - #4 

Once we agree on all of those or even more, I'll get started on it.

**Comment by ashleydavis** [comment]
Sounds good... but we should only publish from the `prod` branch (which doesn't exist yet).

We also have to build and release the executable for all platforms.

**Comment by ashleydavis** [comment]
Also I'm thinking it might be good to do "latest" releases and versioned releases.

So any merge and push to `prod` should build "latest".

But to build a versioned release we'd have to tag the relevant commit with a label.

I've done similar for my Authentic project: https://github.com/ashleydavis/authentic/blob/main/.github/workflows/main.yml

@R4meau if you want to work on this please show me a prototype first in a separate project, then we can talk about how to integrate it.

**Comment by R4meau** [comment]
Sounds great! Didn't know about Authentic.

Interesting project. Alright, I'll create a prototype first.

**Comment by ashleydavis** [comment]
Yeah I think separate prototypes are good way to work. That way we can experiment and learn before we try to integrate into Doulevo.

Also Doulevo already comes with some baggage, when you build a prototype you are allowed to discard the baggage and be free to try and idea without risk. Don't try and make it perfect though. It just has to answer the question "how will this work" and then it's ready to show.

If you want to share a prototype you can give to me by zip file or by Git repo. Really good prototypes that can help other people, we might add them to the Doulevo repo as examples, for example these early ones that I did:
https://github.com/doulevo/handlebars-template-prototype
https://github.com/doulevo/build-system-test

**Comment by R4meau** [comment]
I get the idea. Thanks!

**Comment by R4meau** [comment]
I created the prototype over there - https://github.com/R4meau/say-hi-npm

The PR is #25
