### ISSUE TITLE
Doulevo testing

### ISSUE THREAD

**Issue by ashleydavis** [doulevo/doulevo#4]
Doulevo is currently a bit light on automated testing because we are currently working towards a tech demo.

There is a testing framework in place and some tests have already been written.

However most commands and services still need to have tests written for them.

**Comment by R4meau** [comment]
We should also implement Continuous Integration by creating a GitHub action that runs jobs on pull requests. I can implement it while I implement #20

**Comment by ashleydavis** [comment]
Sounds great, the deployment should happen only for the `prod` branch, but CI can should run on any branch.
